version: 1.0.0
metadata:
  profile: development
  name: ve-ibm
  description: Virtual Environment for Individual-Based Modeling
rootDir: .
outDir: ../../
paths:
  sample: samples
  graph: graphs
app:
  threshold: 1e-7
  counter: 5
  rain:
      divisor: 10
      values:
        - 20
        - 200
        - 600
        - 30
        - 0
        - 0
  habitats: # not being used yet
    # - id: orange_sm
    #   name: lagoon-orange-sm
    #   type: 1
    #   capacity: 20
    #   label: ~
    #   props:
    #     water: ~
    #     salinity: ~
    #     food: ~
    #   design:
    #     color: ~
    #     filled: ~
    #     verts: ~
    # - id: orange_lg
    #   name: lagoon-orange-sm
    #   type: 1
    #   capacity: 20
    #   props:
    #     water: ~
    #     salinity: ~
    #     food: ~
    #   design:
    #     color: ~
    #     filled: ~
    #     verts: ~
    # - id: blue
    #   name: lagoon-orange-sm
    #   type: 2
    #   capacity: 20
    #   props:
    #     water: ~
    #     salinity: ~
    #     food: ~
    #   design:
    #     color: ~
    #     filled: ~
    #     verts: ~
    # - id: green
    #   name: lagoon-orange-sm
    #   type: 3
    #   capacity: 20
    # - id: human1
    #   name: human-settlement
    #   type: human
    #   capacity: ~
    #   props:
    #     water: ~
    #     salinity: ~
    #     food: ~
    #   design:
    #     color: ~
    #     filled: ~
    #     verts: ~
  agents:
    - type: 5cm
      quantity: 5
      color: '#6CC2BD'
      label: 5cm-legged
      habs:
      - 1
      fns:
        - penv: w
          def: 'lambda x: -0.00002*x**5 + 0.0028*x**4 - 0.1551*x**3 + 4.0552*x**2 - 48.806*x + 213.64'
          args:
            - x
          deps:
        - penv: s
          def: 'lambda s: 0.00006 * s**2 + 0.0002 * s + 0.0004'
          args:
            - s
          deps:
        - penv: f
          def: 'lambda f: (0.00673 * f**2) - (0.002936 * f) + 0.5'
          args:
            - f
          deps:
        - penv: d
          def: 'lambda d: -0.0013 * d**2 + 0.0074 * d - 0.0001'
          args:
            - d
          deps:
    - type: 10cm
      quantity: 4
      color: '#5A809E'
      label: 10cm-legged
      habs:
        - 1
      fns:
        - penv: w
          def: 'lambda x: 0.00009*x**4 - 0.0129*x**3 + 0.6696*x**2 - 14.75*x + 114.18'
          args:
            - x
          deps:
        - penv: s
          def: 'lambda s: 0.00006 * s**2 + 0.0002 * s + 0.0004'
          args:
            - s
          deps:
        - penv: f
          def: 'lambda f: (0.00673 * f**2) - (0.002936 * f) + 0.5'
          args:
            - f
          deps:
        - penv: d
          def: 'lambda d: -0.0013 * d**2 + 0.0074 * d - 0.0001'
          args:
            - d
          deps:
    - type: 30cm
      quantity: 7
      color: '#7C79A2'
      label: 30cm-legged
      habs:
        - 1
        - 2
      fns:
        - penv: w
          def: 'lambda x: -10.89*math.log(x) + 44.71'
          args:
            - x
          deps:
            - 'import math'
        - penv: s
          def: 'lambda s: 0.00006 * s**2 + 0.0002 * s + 0.0004'
          args:
            - s
          deps:
        - penv: f
          def: 'lambda f: (0.00673 * f**2) - (0.002936 * f) + 0.5'
          args:
            - f
          deps:
        - penv: d
          def: 'lambda d: -0.0013 * d**2 + 0.0074 * d - 0.0001'
          args:
            - d
          deps:
    - type: 60cm
      quantity: 6
      color: '#F57D7C'
      label: 60cm-legged
      fn:
        def: 'lambda: 12.5'
        args:
      habs:
        - 1
        - 2
        - 3
      fns:
        - penv: w
          def: 'lambda: 12.5'
          args:
          deps:
        - penv: s
          def: 'lambda s: 0.00006 * s**2 + 0.0002 * s + 0.0004'
          args:
            - s
          deps:
        - penv: f
          def: 'lambda f: (0.00673 * f**2) - (0.002936 * f) + 0.5'
          args:
            - f
          deps:
        - penv: d
          def: 'lambda d: -0.0013 * d**2 + 0.0074 * d - 0.0001'
          args:
            - d
          deps: